### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by 15966697671** [Zzh-tju/DIoU-SSD-pytorch#3]
(pyssd) nyj@nyj-desktop:~/DIoU-SSD-pytorch-master$ python tools/train.py
VOC
Traceback (most recent call last):
  File "tools/train.py", line 291, in <module>
    train()
  File "tools/train.py", line 103, in train
    parser.error('Must specify dataset_root if specifying dataset')
  File "/home/nyj/yes/envs/pyssd/lib/python3.7/argparse.py", line 2499, in error
    self.print_usage(_sys.stderr)
  File "/home/nyj/yes/envs/pyssd/lib/python3.7/argparse.py", line 2469, in print_usage
    self._print_message(self.format_usage(), file)
  File "/home/nyj/yes/envs/pyssd/lib/python3.7/argparse.py", line 2435, in format_usage
    return formatter.format_help()
  File "/home/nyj/yes/envs/pyssd/lib/python3.7/argparse.py", line 284, in format_help
    help = self._root_section.format_help()
  File "/home/nyj/yes/envs/pyssd/lib/python3.7/argparse.py", line 215, in format_help
    item_help = join([func(*args) for func, args in self.items])
  File "/home/nyj/yes/envs/pyssd/lib/python3.7/argparse.py", line 215, in <listcomp>
    item_help = join([func(*args) for func, args in self.items])
  File "/home/nyj/yes/envs/pyssd/lib/python3.7/argparse.py", line 322, in _format_usage
    action_usage = format(optionals + positionals, groups)
  File "/home/nyj/yes/envs/pyssd/lib/python3.7/argparse.py", line 397, in _format_actions_usage
    start = actions.index(group._group_actions[0])
IndexError: list index out of range

When run this command:
` python tools/train.py`
this question happened. And, I put these 3 lines:
> import sys
> sys.argv=['']
> del sys

It didn't solved.
How to solve it? Thank you!

**Comment by Zzh-tju** [comment]
I will check it and give you response tomorrow. Or you can refer to (https://github.com/JaryHuang/awesome_SSD_FPN_GIoU).

**Comment by Zzh-tju** [comment]
Your VOC dataset must be put as the following structure.
Here is my way:
|---data
|       |--VOCdevkit
|       |         |----VOC2007
|       |         |----VOC2012
By the way, my conda env is python 3.6.

**Comment by Zzh-tju** [comment]
Your VOC dataset must be put as the following structure.
Here is my way:
|---data
|---- |--VOCdevkit
|-----|----|----VOC2007
|-----|----|----VOC2012
By the way, my conda env is python 3.6.

**Comment by 15966697671** [comment]
> Your VOC dataset must be put as the following structure.
> Here is my way:
> |---data
> |---- |--VOCdevkit
> |-----|----|----VOC2007
> |-----|----|----VOC2012
> By the way, my conda env is python 3.6.

My VOC dataset also put  like you. my conda env is python 3.7.

**Comment by bellzhong677** [comment]
Hello, I met the same problem as you, how did you solve it
